/*
 * generated by Xtext 2.11.0
 */
package org.moflon.emf.injection.ide


/**
 * Use this class to register ide components.
 */
class InjectionLanguageIdeModule extends AbstractInjectionLanguageIdeModule {
}
