name: Validate eMoflon-core versions
on:
  push

env:
  VERSION: "1.7.0"

jobs:
  # Validate updatesite 'site.xml' file
  validate-site-xml:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          SITEXMLFILE="./org.moflon.core.releng.updatesite/site.xml"
          exec 1>&2
          NUMZEROS=$(grep "version=\"$VERSION.qualifier\">" $SITEXMLFILE | wc -l)
          NUMVERS=$(grep -o -P '(?<=version=\").*(?=.qualifier\">)' $SITEXMLFILE | wc -l)
          if [ $NUMZEROS -ne $NUMVERS ]; then echo "site.xml has versions != $VERSION" && exit 1; fi

  # Validate all 'feature.xml' files
  validate-feature-xml:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          MATCHFOUND=false
          FOUNDFILES=$(find . -name "feature.xml") 
          for FILE in $FOUNDFILES; do
              echo "Processing file $FILE";
              NUMMATCHES=$(grep "match=" $FILE | wc -l);
              if [ $NUMMATCHES -ne "0" ]; then echo "$FILE includes dependency \"match=\" (hard-coded versions)" && MATCHFOUND=true; fi;
          done
          if [ "$MATCHFOUND" = true ]; then echo "Check failed!" && exit 1; fi
